codeunit 50159 "KINTO Test Number Series"
{
    Subtype = Test;
    TestPermissions = Disabled;

    var
        Assert: Codeunit "Library Assert";
        TestSetup: Codeunit "KINTO Test Setup";

    [Test]
    procedure TestQuoteNoAutoGenerated()
    var
        CountrySetup: Record "KINTO Country Setup";
        QuoteHeader: Record "KINTO Quote Header";
    begin
        TestSetup.CleanupTestData();
        TestSetup.SetupCountrySetupBR(CountrySetup);
        TestSetup.SetupQuoteHeader(QuoteHeader, 'BR');

        Assert.IsTrue(QuoteHeader."Quote No." <> '', 'Quote No. should be auto-generated');
        Assert.IsTrue(StrPos(QuoteHeader."Quote No.", 'Q-') = 1, 'Quote No. should start with Q-');
        Assert.IsTrue(QuoteHeader."No. Series" = 'KINTO-QUOTE', 'No. Series should be KINTO-QUOTE');
    end;

    [Test]
    procedure TestSnapshotIDAutoGenerated()
    var
        CountrySetup: Record "KINTO Country Setup";
        VehicleModel: Record "KINTO Vehicle Model";
        RVMatrix: Record "KINTO RV Matrix";
        MaintHeader: Record "KINTO Maintenance Plan Header";
        MaintLine: Record "KINTO Maintenance Plan Line";
        QuoteHeader: Record "KINTO Quote Header";
        QuoteItem: Record "KINTO Quote Item";
        Snapshot: Record "KINTO Simulation Snapshot";
        PricingEngine: Codeunit "KINTO Pricing Engine Mgt.";
    begin
        TestSetup.CleanupTestData();
        TestSetup.SetupCountrySetupBR(CountrySetup);
        TestSetup.SetupVehicleModel(VehicleModel);
        TestSetup.SetupRVMatrix(RVMatrix, 'CC-XRE');
        TestSetup.SetupMaintenancePlan(MaintHeader, MaintLine);
        TestSetup.SetupQuoteHeader(QuoteHeader, 'BR');
        TestSetup.SetupQuoteItem(QuoteItem, QuoteHeader."Quote No.");

        PricingEngine.RunPricing(QuoteHeader);

        QuoteHeader.Get(QuoteHeader."Quote No.");
        Assert.IsTrue(QuoteHeader."Snapshot ID" <> '', 'Snapshot ID should be auto-generated');
        Assert.IsTrue(StrPos(QuoteHeader."Snapshot ID", 'SNP-') = 1, 'Snapshot ID should start with SNP-');
        Assert.IsTrue(Snapshot.Get(QuoteHeader."Snapshot ID"), 'Snapshot should be retrievable');
    end;

    [Test]
    procedure TestExpirationDateAutoCalculated()
    var
        CountrySetup: Record "KINTO Country Setup";
        QuoteHeader: Record "KINTO Quote Header";
        ExpectedDate: Date;
    begin
        TestSetup.CleanupTestData();
        TestSetup.SetupCountrySetupBR(CountrySetup);
        TestSetup.SetupQuoteHeader(QuoteHeader, 'BR');

        // Validity Period = 30 days
        ExpectedDate := CalcDate('+30D', Today);
        Assert.AreEqual(ExpectedDate, QuoteHeader."Expiration Date", 'Expiration date should be Today + 30 days');
    end;
}