table 50114 "KINTO Simulation Snapshot"
{
    Caption = 'KINTO Simulation Snapshot';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Entry No."; Integer) { Caption = 'Entry No.'; AutoIncrement = true; }
        field(2; "Snapshot ID"; Code[20]) { Caption = 'Snapshot ID'; }
        field(3; "Quote No."; Code[20]) { Caption = 'Quote No.'; TableRelation = "KINTO Quote Header"; }
        field(4; "Quote Line No."; Integer) { Caption = 'Quote Line No.'; }
        field(5; "Generated By"; Code[50]) { Caption = 'Generated By'; }
        field(6; "Created DateTime"; DateTime) { Caption = 'Created DateTime'; }
        field(7; "Status"; Option) { Caption = 'Status'; OptionMembers = Draft,Calculated,Archived; }
        field(10; "Vehicle Model No."; Code[20]) { Caption = 'Vehicle Model'; }
        field(11; "Vehicle Variant"; Code[20]) { Caption = 'Vehicle Variant'; }
        field(12; "Usage Type"; Enum "KINTO Usage Type") { Caption = 'Usage Type'; }
        field(20; "Lead Time"; Integer) { Caption = 'Lead Time (days)'; }
        field(21; "Contract Term"; Integer) { Caption = 'Contract Term (months)'; }
        field(22; "Monthly Mileage"; Decimal) { Caption = 'Monthly Mileage'; }
        field(23; "Payment Allowance"; Integer) { Caption = 'Payment Allowance (days)'; }
        field(24; "Contract Start Month"; Integer) { Caption = 'Contract Start Month'; }
        field(30; "Annual Inflation %"; Decimal) { Caption = 'Annual Inflation %'; DecimalPlaces = 0 : 5; }
        field(31; "Tire Inflation %"; Decimal) { Caption = 'Tire Inflation %'; DecimalPlaces = 0 : 5; }
        field(32; "Ref. Interest Rate"; Decimal) { Caption = 'Reference Interest Rate'; DecimalPlaces = 0 : 5; }
        field(33; "Spread"; Decimal) { Caption = 'Spread'; DecimalPlaces = 0 : 5; }
        field(34; "Idleness Rate"; Decimal) { Caption = 'Idleness Rate'; DecimalPlaces = 0 : 5; }
        field(35; "Interest Expense"; Decimal) { Caption = 'Interest Expense'; }
        field(40; "MSRP"; Decimal) { Caption = 'MSRP'; }
        field(41; "Total Equipment Price"; Decimal) { Caption = 'Total Equipment Price'; }
        field(42; "Purchase Price"; Decimal) { Caption = 'Purchase Price'; }
        field(43; "Depreciation Market %"; Decimal) { Caption = 'Depreciation Market %'; DecimalPlaces = 0 : 5; }
        field(44; "Final Resale Price"; Decimal) { Caption = 'Final Resale Price'; }
        field(45; "SGA"; Decimal) { Caption = 'SG&A'; }
        field(46; "Target ROI"; Decimal) { Caption = 'Target ROI'; DecimalPlaces = 0 : 5; }
        field(47; "Standard Target ROI"; Decimal) { Caption = 'Standard Target ROI'; DecimalPlaces = 0 : 5; }
        field(50; "Monthly Fee"; Decimal) { Caption = 'Monthly Fee'; }
        field(51; "Negotiated Monthly Price"; Decimal) { Caption = 'Negotiated Monthly Price'; }
        field(52; "EBT"; Decimal) { Caption = 'EBT'; }
        field(53; "PAT"; Decimal) { Caption = 'PAT'; }
        field(54; "IRR"; Decimal) { Caption = 'IRR'; DecimalPlaces = 0 : 10; }
        field(55; "Reference IRR"; Decimal) { Caption = 'Reference IRR'; DecimalPlaces = 0 : 10; }
        field(56; "Calculated ROI"; Decimal) { Caption = 'Calculated ROI'; DecimalPlaces = 0 : 10; }
        field(60; "Incl. Preventive Maint."; Boolean) { Caption = 'Incl. Preventive Maint.'; }
        field(61; "Incl. Corrective Maint."; Boolean) { Caption = 'Incl. Corrective Maint.'; }
        field(62; "Number of Tires"; Integer) { Caption = 'Number of Tires'; }
        field(63; "Tire in Pool"; Boolean) { Caption = 'Tire in Pool'; }
        field(70; "Body Coverage"; Decimal) { Caption = 'Body Coverage'; }
        field(71; "Cov. Material Damages"; Decimal) { Caption = 'Material Damages Coverage'; }
        field(72; "Cov. Personal Damages"; Decimal) { Caption = 'Personal Damages Coverage'; }
        field(73; "Cov. Moral Damages"; Decimal) { Caption = 'Moral Damages Coverage'; }
        field(74; "Cov. Death Benefit"; Decimal) { Caption = 'Death Benefit Coverage'; }
        field(75; "Cov. Perm. Disability"; Decimal) { Caption = 'Permanent Disability Coverage'; }
        field(76; "Deductibles"; Decimal) { Caption = 'Deductibles'; }
        field(77; "Glass Coverage Type"; Text[30]) { Caption = 'Glass Coverage Type'; }
        field(80; "Participates in Pool"; Boolean) { Caption = 'Participates in Pool'; }
        field(81; "Price Excess km 10%"; Decimal) { Caption = 'Price per excess km up to 10%'; }
        field(82; "Price Excess km >10%"; Decimal) { Caption = 'Price per excess km above 10%'; }
        field(83; "Over-Mileage Rules"; Text[250]) { Caption = 'Over-Mileage Rules'; }
        field(84; "Armoring"; Boolean) { Caption = 'Armoring'; }
        field(85; "Adjustment Index"; Text[30]) { Caption = 'Adjustment Index'; }
        field(86; "Adjustment Period"; Option) { Caption = 'Adjustment Period'; OptionMembers = No,Monthly,Annually; }
        field(87; "Admin Fee"; Decimal) { Caption = 'Admin Fee'; }
        field(88; "Fine Admin Fee"; Decimal) { Caption = 'Fine Admin Fee'; }
        field(89; "Non-Withdrawal Fee"; Decimal) { Caption = 'Non-Withdrawal Fee'; }
        field(90; "Advanced Post"; Boolean) { Caption = 'Advanced Post'; }
        field(91; "Deadline Police Rep."; Text[30]) { Caption = 'Deadline Police Report'; }
        field(92; "Reimbursement Due Date"; Text[30]) { Caption = 'Reimbursement Due Date'; }
        field(93; "Delivery Spare Vehicle"; Text[50]) { Caption = 'Delivery Spare Vehicle'; }
    }

    keys
    {
        key(PK; "Entry No.") { Clustered = true; }
        key(Idx1; "Snapshot ID") { }
        key(Idx2; "Quote No.", "Quote Line No.") { }
    }

    trigger OnInsert()
    begin
        "Generated By" := UserId;
        "Created DateTime" := CurrentDateTime;
    end;
}