table 50114 "KINTO Simulation Snapshot"
{
    Caption = 'KINTO Simulation Snapshot';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Snapshot ID"; Code[20]) { Caption = 'Snapshot ID'; }
        field(2; "Quote No."; Code[20]) { Caption = 'Quote No.'; TableRelation = "KINTO Quote Header"; }
        field(3; "Quote Line No."; Integer) { Caption = 'Quote Line No.'; }
        field(4; "Generated By"; Code[50]) { Caption = 'Generated By'; }
        field(5; "Created DateTime"; DateTime) { Caption = 'Created DateTime'; }
        field(6; "Vehicle Model No."; Code[20]) { Caption = 'Vehicle Model'; }
        field(7; "Vehicle Variant"; Code[20]) { Caption = 'Vehicle Variant'; }
        field(8; "Usage Type"; Enum "KINTO Usage Type") { Caption = 'Usage Type'; }
        field(9; "Lead Time"; Integer) { Caption = 'Lead Time (days)'; }
        field(10; "Contract Term"; Integer) { Caption = 'Contract Term (months)'; }
        field(11; "Monthly Mileage"; Decimal) { Caption = 'Monthly Mileage'; }
        field(12; "Payment Allowance"; Integer) { Caption = 'Payment Allowance (days)'; }
        field(13; "Annual Inflation %"; Decimal) { Caption = 'Annual Inflation %'; DecimalPlaces = 0 : 5; }
        field(14; "Tire Inflation %"; Decimal) { Caption = 'Tire Inflation %'; DecimalPlaces = 0 : 5; }
        field(15; "Ref. Interest Rate"; Decimal) { Caption = 'Reference Interest Rate'; DecimalPlaces = 0 : 5; }
        field(16; "Spread"; Decimal) { Caption = 'Spread'; DecimalPlaces = 0 : 5; }
        field(17; "Idleness Rate"; Decimal) { Caption = 'Idleness Rate'; DecimalPlaces = 0 : 5; }
        field(18; "Negotiation Margin %"; Decimal) { Caption = 'Achieved Negotiation Margin %'; DecimalPlaces = 0 : 5; }
        field(19; "PIS COFINS Tariff %"; Decimal) { Caption = 'PIS/COFINS on Tariff'; DecimalPlaces = 0 : 5; }
        field(20; "PIS COFINS Credit %"; Decimal) { Caption = 'PIS/COFINS Credit on Depreciation'; DecimalPlaces = 0 : 5; }
        field(21; "Tax Depreciation Period"; Integer) { Caption = 'Tax Depreciation Period'; }
        field(22; "Interest Expense"; Decimal) { Caption = 'Interest Expense'; }
        field(23; "Net of Taxes for ROI"; Boolean) { Caption = 'Net of Taxes and Fees for ROI'; }
        field(24; "Insurance Tax"; Decimal) { Caption = 'Insurance Tax (e.g. IOF)'; }
        field(25; "Profit Tax Rate %"; Decimal) { Caption = 'Profit Tax Rate'; DecimalPlaces = 0 : 5; }
        field(26; "Credit Risk Factor"; Decimal) { Caption = 'Credit Risk Factor'; DecimalPlaces = 0 : 5; }
        field(27; "Mfr. Sales Comm. %"; Decimal) { Caption = 'Manufacturer Sales Commission %'; DecimalPlaces = 0 : 5; }
        field(28; "Mfr. Delivery Comm. %"; Decimal) { Caption = 'Manufacturer Delivery Commission %'; DecimalPlaces = 0 : 5; }
        field(29; "Total Mfr. Discount %"; Decimal) { Caption = 'Total Manufacturer Discount %'; DecimalPlaces = 0 : 5; }
        field(30; "KINTO Sales Comm. %"; Decimal) { Caption = 'KINTO Commission – Sales %'; DecimalPlaces = 0 : 5; }
        field(31; "KINTO Delivery Comm. %"; Decimal) { Caption = 'KINTO Commission – Delivery %'; DecimalPlaces = 0 : 5; }
        field(32; "Target ROI"; Decimal) { Caption = 'User-defined Target ROI'; DecimalPlaces = 0 : 5; }
        field(33; "Contract Start Month"; Integer) { Caption = 'Contract Start Month'; }
        field(34; "MSRP"; Decimal) { Caption = 'MSRP'; }
        field(35; "Total Equipment Price"; Decimal) { Caption = 'Total Equipment Price'; }
        field(36; "Purchase Price"; Decimal) { Caption = 'Purchase Price'; }
        field(37; "Depreciation Market %"; Decimal) { Caption = 'Depreciation Market %'; DecimalPlaces = 0 : 5; }
        field(38; "Final Resale Price"; Decimal) { Caption = 'Final Resale Price'; }
        field(39; "SGA"; Decimal) { Caption = 'SG&A'; }
        field(40; "Mileage Start"; Decimal) { Caption = 'Mileage Start'; }
        field(41; "Mileage End"; Decimal) { Caption = 'Mileage End'; }
        field(42; "Standard Target ROI"; Decimal) { Caption = 'Standard Target ROI'; DecimalPlaces = 0 : 5; }
        field(43; "EBT"; Decimal) { Caption = 'EBT'; }
        field(44; "PAT"; Decimal) { Caption = 'PAT'; }
        field(45; "IRR"; Decimal) { Caption = 'IRR'; DecimalPlaces = 0 : 10; }
        field(46; "Reference IRR"; Decimal) { Caption = 'Reference IRR'; DecimalPlaces = 0 : 10; }
        field(47; "Calculated ROI"; Decimal) { Caption = 'Calculated ROI'; DecimalPlaces = 0 : 10; }
        field(48; "Monthly Fee"; Decimal) { Caption = 'Calculated/Minimum Monthly Fee'; }
        field(49; "Negotiated Monthly Price"; Decimal) { Caption = 'Negotiated Monthly Price'; }
        field(50; "Status"; Enum "KINTO Pricing Status") { Caption = 'Status'; }
        field(51; "Message"; Text[250]) { Caption = 'Message'; }
        field(52; "Participates in Pool"; Boolean) { Caption = 'Participates in Pool'; }
        field(53; "Price Excess km 10%"; Decimal) { Caption = 'Price per excess km up to 10%'; }
        field(54; "Price Excess km >10%"; Decimal) { Caption = 'Price per excess km above 10%'; }
        field(55; "Over-Mileage Rules"; Text[250]) { Caption = 'Over-Mileage Billing Rules'; }
        field(56; "Incl. Preventive Maint."; Boolean) { Caption = 'Inclusion of preventive maintenance'; }
        field(57; "Incl. Corrective Maint."; Boolean) { Caption = 'Inclusion of corrective maintenance'; }
        field(58; "Number of Tires"; Integer) { Caption = 'Number of tires included'; }
        field(59; "Tire in Pool"; Boolean) { Caption = 'Tire Maintenance in pool or not'; }
        field(60; "Replacement Vehicle Days"; Integer) { Caption = 'Number of rental days for replacement vehicle'; }
        field(61; "Replacement Vehicle Model"; Text[50]) { Caption = 'Replacement vehicle model'; }
        field(62; "Replacement in Pool"; Boolean) { Caption = 'Replacement vehicle in pool or not'; }
        field(63; "Body Coverage"; Boolean) { Caption = 'Insurance coverage for vehicle body'; }
        field(64; "Cov. Material Damages"; Boolean) { Caption = 'Coverage values - material damages'; }
        field(65; "Cov. Personal Damages"; Boolean) { Caption = 'Coverage values - personal damages'; }
        field(66; "Cov. Moral Damages"; Boolean) { Caption = 'Coverage values - moral damages'; }
        field(67; "Cov. Death Benefit"; Boolean) { Caption = 'Coverage values - Death Benefit'; }
        field(68; "Cov. Perm. Disability"; Boolean) { Caption = 'Coverage values - Permanent Disability Benefit'; }
        field(69; "Deductibles"; Boolean) { Caption = 'Deductibles'; }
        field(70; "Glass Coverage Type"; Text[30]) { Caption = 'Type of glass coverage'; }
        field(71; "Armoring"; Boolean) { Caption = 'Inclusion of armoring'; }
        field(72; "Adjustment Index"; Text[30]) { Caption = 'Applied adjustment index'; }
        field(73; "Adjustment Period"; Option) { Caption = 'Adjustment period for monthly fee'; OptionMembers = No,Monthly,Annually; }
        field(74; "Admin Fee"; Decimal) { Caption = 'Administrative fee'; }
        field(75; "Fine Admin Fee"; Decimal) { Caption = 'Fine Administration Fee – Per Event'; }
        field(76; "Non-Withdrawal Fee"; Decimal) { Caption = 'Expense for Non-Withdrawal – Per Day'; }
        field(77; "Advanced Post"; Boolean) { Caption = 'Advanced Post'; }
        field(78; "Deadline Police Rep."; Text[30]) { Caption = 'Deadline to Submit Police Report'; }
        field(79; "Reimbursement Due Date"; Text[30]) { Caption = 'Reimbursement Due Date'; }
        field(80; "Delivery Spare Vehicle"; Text[50]) { Caption = 'Delivery of Spare Vehicle'; }
    }

    keys
    {
        key(PK; "Snapshot ID") { Clustered = true; }
        key(Idx1; "Quote No.", "Quote Line No.") { }
    }

    trigger OnInsert()
    begin
        "Created DateTime" := CurrentDateTime;
        "Generated By" := UserId;
    end;
}