page 50115 "KINTO Snapshot Card"
{
    Caption = 'Simulation Snapshot';
    PageType = Card;
    SourceTable = "KINTO Simulation Snapshot";
    ApplicationArea = All;

    layout
    {
        area(Content)
        {
            group(General)
            {
                field("Snapshot ID"; Rec."Snapshot ID") { ApplicationArea = All; }
                field("Quote No."; Rec."Quote No.") { ApplicationArea = All; }
                field("Quote Line No."; Rec."Quote Line No.") { ApplicationArea = All; }
                field("Generated By"; Rec."Generated By") { ApplicationArea = All; }
                field("Created DateTime"; Rec."Created DateTime") { ApplicationArea = All; }
                field("Status"; Rec."Status") { ApplicationArea = All; }
            }
            group(Vehicle)
            {
                field("Vehicle Model No."; Rec."Vehicle Model No.") { ApplicationArea = All; }
                field("Vehicle Variant"; Rec."Vehicle Variant") { ApplicationArea = All; }
                field("Usage Type"; Rec."Usage Type") { ApplicationArea = All; }
            }
            group(Contract)
            {
                field("Lead Time"; Rec."Lead Time") { ApplicationArea = All; }
                field("Contract Term"; Rec."Contract Term") { ApplicationArea = All; }
                field("Monthly Mileage"; Rec."Monthly Mileage") { ApplicationArea = All; }
                field("Payment Allowance"; Rec."Payment Allowance") { ApplicationArea = All; }
                field("Contract Start Month"; Rec."Contract Start Month") { ApplicationArea = All; }
            }
            group(Financial)
            {
                field("Annual Inflation %"; Rec."Annual Inflation %") { ApplicationArea = All; }
                field("Tire Inflation %"; Rec."Tire Inflation %") { ApplicationArea = All; }
                field("Ref. Interest Rate"; Rec."Ref. Interest Rate") { ApplicationArea = All; }
                field("Spread"; Rec."Spread") { ApplicationArea = All; }
                field("Idleness Rate"; Rec."Idleness Rate") { ApplicationArea = All; }
                field("Interest Expense"; Rec."Interest Expense") { ApplicationArea = All; }
            }
            group(Pricing)
            {
                field("MSRP"; Rec."MSRP") { ApplicationArea = All; }
                field("Total Equipment Price"; Rec."Total Equipment Price") { ApplicationArea = All; }
                field("Purchase Price"; Rec."Purchase Price") { ApplicationArea = All; }
                field("Depreciation Market %"; Rec."Depreciation Market %") { ApplicationArea = All; }
                field("Final Resale Price"; Rec."Final Resale Price") { ApplicationArea = All; }
                field("SGA"; Rec."SGA") { ApplicationArea = All; }
                field("Target ROI"; Rec."Target ROI") { ApplicationArea = All; }
                field("Standard Target ROI"; Rec."Standard Target ROI") { ApplicationArea = All; }
            }
            group(Results)
            {
                field("Monthly Fee"; Rec."Monthly Fee") { ApplicationArea = All; }
                field("Negotiated Monthly Price"; Rec."Negotiated Monthly Price") { ApplicationArea = All; }
                field("EBT"; Rec."EBT") { ApplicationArea = All; }
                field("PAT"; Rec."PAT") { ApplicationArea = All; }
                field("IRR"; Rec."IRR") { ApplicationArea = All; }
                field("Reference IRR"; Rec."Reference IRR") { ApplicationArea = All; }
                field("Calculated ROI"; Rec."Calculated ROI") { ApplicationArea = All; }
            }
        }
    }
}